name: "RecruitmentInformation"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"

jobs:
  GetRecruitmentInformation:
    runs-on: ubuntu-latest
    steps:
      - name: "Set python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade requests

      - name: "Get recruitmentInformation and send message ..."
        env:
          UID: ${{ secrets.UID }}
          APPTOKEN: ${{ secrets.APPTOKEN }}
        run: |
          wget -O "RecruitmentInformation.zip" '${{ secrets.DOWNLOADURL }}'
          unzip -o "RecruitmentInformation.zip" -d "$(pwd)/"
          python RecruitmentInformation.py